/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.12
 * Generated at: 2022-04-25 22:49:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<title>Ejercicio Formulario</title>\n");
      out.write("<!-- 		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"> -->\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/styles.css\">\n");
      out.write("		<script type=\"text/javascript\" src=\"resources/functions.js\"></script>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		<form name=\"form1\" action=\"servlet\" method=\"POST\" onSubmit=\"return validarForma(this)\"><!-- El formulario responde al servlet del action -->\n");
      out.write("			<input type=\"hidden\" name=\"oculto\" value=\"valorOculto\"></input>\n");
      out.write("			<table width=\"200\" id=\"enfasis-columna\">\n");
      out.write("				<caption>Formulario Registro de Datos</caption>\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"columna\">Usuario: (*)</td>\n");
      out.write("					<td>\n");
      out.write("						<input class=\"default\" type=\"text\" name=\"usuario\" placeholder=\"Escribir usuario\"></input>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"columna\">Password: (*)</td>\n");
      out.write("					<td>\n");
      out.write("						<input class=\"default\" type=\"password\" name=\"password\" placeholder=\"Escribir password\"></input>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"columna\">Tecnologías de Internet: (*)</td>\n");
      out.write("					<td>\n");
      out.write("						<span>Java<input type=\"checkbox\" name=\"tecnologia\" value=\"java\"/></span>\n");
      out.write("						<span>.NET<input type=\"checkbox\" name=\"tecnologia\" value=\"net\"/></span>\n");
      out.write("						<span>PHP<input type=\"checkbox\" name=\"tecnologia\" value=\"php\"/></span>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"columna\">Género: (*)</td>\n");
      out.write("					<td>\n");
      out.write("						Hombre<input type=\"radio\" name=\"genero\" value=\"H\"/>\n");
      out.write("						Mujer<input type=\"radio\" name=\"genero\" value=\"M\"/>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"columna\">Ocupación: (*)</td>\n");
      out.write("					<td>\n");
      out.write("						<select name=\"ocupacion\" class=\"default\">\n");
      out.write("							<option value=\"\">Seleccionar...</option>\n");
      out.write("							<option value=\"1\">Profesor</option>\n");
      out.write("							<option value=\"2\">Ingeniero</option>\n");
      out.write("							<option value=\"3\">Jubilado</option>\n");
      out.write("							<option value=\"4\">Otro</option>\n");
      out.write("						</select>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"columna\">Música favorita:</td>\n");
      out.write("					<td>\n");
      out.write("						<select name=\"musica\" multiple class=\"default\">\n");
      out.write("							<option value=\"rock\">Rock</option>\n");
      out.write("							<option value=\"pop\">Pop</option>\n");
      out.write("							<option value=\"salsa\">Salsa</option>\n");
      out.write("						</select>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td class=\"columna\">Comentarios:</td>\n");
      out.write("					<td>\n");
      out.write("						<textarea rows=\"2\" cols=\"30\" name=\"comentarios\" class=\"default\" placeholder=\"Escribe un texto\"></textarea>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr style=\"text-align: center;\">\n");
      out.write("					<td>\n");
      out.write("						<input type=\"reset\" value=\"Limpiar\" class=\"default\"/>\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"submit\" value=\"Enviar\" class=\"default\"/>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</form>\n");
      out.write("	</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
